<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTcvSy8l\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTcvSy8l/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTcvSy8l.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTcvSy8l\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTcvSy8l\App_KernelDevDebugContainer([
    'container.build_hash' => 'TcvSy8l',
    'container.build_id' => '11971793',
    'container.build_time' => 1575897425,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTcvSy8l');
