<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMxKQitN\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMxKQitN/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMxKQitN.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMxKQitN\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMxKQitN\App_KernelDevDebugContainer([
    'container.build_hash' => 'MxKQitN',
    'container.build_id' => '8f0f12f3',
    'container.build_time' => 1574877248,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMxKQitN');
