<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVniUCeF\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVniUCeF/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVniUCeF.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVniUCeF\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVniUCeF\App_KernelDevDebugContainer([
    'container.build_hash' => 'VniUCeF',
    'container.build_id' => 'ae2c271d',
    'container.build_time' => 1575242984,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVniUCeF');
